# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -p:TargetFramework=net8.0 -p:RuntimeIdentifier=win-x64 -p:SelfContained=true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:Configuration=Release -p:PublishReadyToRunComposite=true -p:DebugType=none -p:OptimizationPreference=Speed -p:PublishTrimmed=true -p:TrimMode=full -p:EnableTrimAnalyzer=true -p:TrimmerRemoveSymbols=true -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:EventSourceSupport=false -p:HttpActivityPropagationSupport=false -p:MetadataUpdaterSupport=false -p:StackTraceSupport=false -p:InvariantGlobalization=false
    - uses: actions/upload-artifact@v3
      with:
        name: Windows (x64)
        path: D:\a\Concept-PHIRegex\Concept-PHIRegex\bin\Release\net8.0\win-x64\publish\Concept-PHIRegex.exe

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -p:RuntimeIdentifier=linux-x64 -p:TargetFramework=net8.0 -p:SelfContained=true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:Configuration=Release -p:PublishReadyToRunComposite=true -p:DebugType=none -p:OptimizationPreference=Speed -p:PublishTrimmed=true -p:TrimMode=full -p:EnableTrimAnalyzer=true -p:TrimmerRemoveSymbols=true -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:EventSourceSupport=false -p:HttpActivityPropagationSupport=false -p:MetadataUpdaterSupport=false -p:StackTraceSupport=false -p:InvariantGlobalization=false
    - uses: actions/upload-artifact@v3
      with:
        name: Linux (x64)
        path: /home/runner/work/Concept-PHIRegex/Concept-PHIRegex/bin/Release/net8.0/linux-x64/publish/Concept-PHIRegex
      
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -p:TargetFramework=net8.0 -p:RuntimeIdentifier=osx-x64 -p:SelfContained=true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:Configuration=Release -p:PublishReadyToRunComposite=true -p:DebugType=none -p:OptimizationPreference=Speed -p:PublishTrimmed=true -p:TrimMode=full -p:EnableTrimAnalyzer=true -p:TrimmerRemoveSymbols=true -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:EventSourceSupport=false -p:HttpActivityPropagationSupport=false -p:MetadataUpdaterSupport=false -p:StackTraceSupport=false -p:InvariantGlobalization=false
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS (x64)
        path: /Users/runner/work/Concept-PHIRegex/Concept-PHIRegex/bin/Release/net8.0/osx-x64/publish/Concept-PHIRegex
