# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_ARGS: None
  PUBLISHXML_PATH: ../.github/workflows/publish-settings.pubxml
  OUTPUT_DIR: ../dotnet_build

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet build --no-restore -f net8.0 -r win-x64 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }} --self-contained true /p:PublishProfile=${{ env.PUBLISHXML_PATH }}
    - uses: actions/upload-artifact@v3
      with:
        name: Windows (x64)
        path: ${{ env.OUTPUT_DIR }}\Concept-PHIRegex.exe

  build-android-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r android-arm64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet build --no-restore -f net8.0 -r android-arm64 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }} --self-contained true -p:PublishProfile=${{ env.PUBLISHXML_PATH }}
    - uses: actions/upload-artifact@v3
      with:
        name: Android (ARM64)
        path: ${{ env.OUTPUT_DIR }}/Concept-PHIRegex

  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-arm64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet build --no-restore -f net8.0 -r osx-arm64 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }} --self-contained true -p:PublishProfile=${{ env.PUBLISHXML_PATH }}
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS (ARM64, Apple M1 or newer)
        path: ${{ env.OUTPUT_DIR }}/Concept-PHIRegex

  build-macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet build --no-restore -f net8.0 -r osx-x64 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }} --self-contained true -p:PublishProfile=${{ env.PUBLISHXML_PATH }}
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS (x64, Intel and Apple Silicon)
        path: ${{ env.OUTPUT_DIR }}/Concept-PHIRegex
