# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Console

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_ARGS: None
  PUBLISHXML_PATH: ${{ github.workspace }}/Properties/PublishProfiles/FolderProfile.pubxml
  OUTPUT_DIR: ${{ github.workspace }}/dotnet_build

jobs:
  Windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -f net8.0 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }}/ -p:PublishProfile=${{ env.PUBLISHXML_PATH }} -p:MyRuntimeIdentifier=win-x64
    - uses: actions/upload-artifact@v3
      with:
        name: Windows (x64)
        path: ${{ env.OUTPUT_DIR }}\publish\Concept-PHIRegex.exe

  # Android-ARM64:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v3
  #     with:
  #       dotnet-version: 8.0.x
  #   - name: Restore dependencies
  #     run: dotnet restore -r android-arm64 /p:PublishReadyToRun=true
  #   - name: Publish
  #     run: dotnet publish --no-restore -f net8.0 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }}/ -p:PublishProfile=${{ env.PUBLISHXML_PATH }} -p:MyRuntimeIdentifier=android-arm64 -p:PublishAot=false /p:PublishReadyToRun=false
  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: Android (ARM64, Experimental)
  #       path: ${{ env.OUTPUT_DIR }}/publish

  MacOS-ARM64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-arm64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -f net8.0 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }}/ -p:PublishProfile=${{ env.PUBLISHXML_PATH }} -p:MyRuntimeIdentifier=osx-arm64
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS (ARM64, Apple M1 or newer)
        path: ${{ env.OUTPUT_DIR }}/publish

  MacOS-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-x64 /p:PublishReadyToRun=true
    - name: Publish
      run: dotnet publish --no-restore -f net8.0 -c Release -p:OutputPath=${{ env.OUTPUT_DIR }}/ -p:PublishProfile=${{ env.PUBLISHXML_PATH }} -p:MyRuntimeIdentifier=osx-x64
    - uses: actions/upload-artifact@v3
      with:
        name: MacOS (x64, Intel and Apple Silicon)
        path: ${{ env.OUTPUT_DIR }}/publish
